apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend-deployment
  namespace: semenkovichdev
spec:
  selector:
    matchLabels:
      app: users-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: users-backend
    spec:
      containers:
        - name: users-backend
          image: users:0.0.1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: users-backend-service
  namespace: semenkovichdev
spec:
  selector:
    app: users-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
